import { query } from "./_generated/server";

export const saudiHospitals = [
  {
    rank: 1,
    name_en: "Dr. Soliman Fakeeh Hospital",
    name_ar: "مستشفى الدكتور سليمان فقيه",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 2,
    name_en: "International Medical Center",
    name_ar: "المركز الطبي الدولي",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 3,
    name_en: "Saudi German Hospital Riyadh",
    name_ar: "المستشفى السعودي الألماني الرياض",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 4,
    name_en: "Saudi German Hospital Jeddah",
    name_ar: "المستشفى السعودي الألماني جدة",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 5,
    name_en: "Dr. Sulaiman Al Habib Hospital",
    name_ar: "مستشفى الدكتور سليمان الحبيب",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 6,
    name_en: "Dallah Hospital",
    name_ar: "مستشفى دله",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 7,
    name_en: "Kingdom Hospital",
    name_ar: "مستشفى المملكة",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 8,
    name_en: "Obeid Specialized Hospital",
    name_ar: "مستشفى عبيد التخصصي",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 9,
    name_en: "Al Hammadi Hospital",
    name_ar: "مستشفى الحمادي",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 10,
    name_en: "Riyadh Care Hospital",
    name_ar: "مستشفى رعاية الرياض",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 11,
    name_en: "Specialized Medical Center Hospital",
    name_ar: "مستشفى المركز التخصصي الطبي",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 12,
    name_en: "Al Mousa Specialist Hospital",
    name_ar: "مستشفى الموسى التخصصي",
    city_en: "Al Ahsa",
    city_ar: "الأحساء",
  },
  {
    rank: 13,
    name_en: "Almana General Hospital",
    name_ar: "مستشفى المانع العام",
    city_en: "Khobar",
    city_ar: "الخبر",
  },
  {
    rank: 14,
    name_en: "Mouwasat Hospital",
    name_ar: "مستشفى المواساة",
    city_en: "Dammam",
    city_ar: "الدمام",
  },
  {
    rank: 15,
    name_en: "Dr. Erfan & Bagedo Hospital",
    name_ar: "مستشفى عرفان وباقدو",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 16,
    name_en: "Jeddah National Hospital",
    name_ar: "مستشفى جدة الوطني",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 17,
    name_en: "Al Mashfa Hospital",
    name_ar: "مستشفى المشفى",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 18,
    name_en: "Green Crescent Hospital",
    name_ar: "مستشفى الهلال الأخضر",
    city_en: "Riyadh",
    city_ar: "الرياض",
  },
  {
    rank: 19,
    name_en: "Al Aziziyah Children Hospital",
    name_ar: "مستشفى العزيزية للأطفال",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
  {
    rank: 20,
    name_en: "Bakhsh Hospital",
    name_ar: "مستشفى بخش",
    city_en: "Jeddah",
    city_ar: "جدة",
  },
];

export const list = query({
  args: {},
  handler: async () => saudiHospitals,
});
