export const saudiCities = [
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Riyadh", cityAr: "الرياض" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Jeddah", cityAr: "جدة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Mecca", cityAr: "مكة المكرمة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Medina", cityAr: "المدينة المنورة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Dammam", cityAr: "الدمام" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Khobar", cityAr: "الخبر" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Dhahran", cityAr: "الظهران" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Taif", cityAr: "الطائف" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Tabuk", cityAr: "تبوك" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Abha", cityAr: "أبها" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Khamis Mushait", cityAr: "خميس مشيط" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Najran", cityAr: "نجران" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Jazan", cityAr: "جازان" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Hail", cityAr: "حائل" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Buraidah", cityAr: "بريدة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Unaizah", cityAr: "عنيزة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Sakaka", cityAr: "سكاكا" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Arar", cityAr: "عرعر" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Al Bahah", cityAr: "الباحة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Yanbu", cityAr: "ينبع" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Jubail", cityAr: "الجبيل" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Al Ahsa", cityAr: "الأحساء" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Qatif", cityAr: "القطيف" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Hofuf", cityAr: "الهفوف" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Rafha", cityAr: "رفحاء" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Al Kharj", cityAr: "الخرج" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Wadi Ad Dawasir", cityAr: "وادي الدواسر" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Bisha", cityAr: "بيشة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Qurayyat", cityAr: "القريات" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Rabigh", cityAr: "رابغ" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Turabah", cityAr: "تربة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Sharurah", cityAr: "شرورة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Afif", cityAr: "عفيف" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Al Majmaah", cityAr: "المجمعة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Dawadmi", cityAr: "الدوادمي" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Ras Tanura", cityAr: "رأس تنورة" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Tarout", cityAr: "تاروت" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Sabya", cityAr: "صبيا" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Muhayil Asir", cityAr: "محايل عسير" },
  { countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", flag: "🇸🇦", cityEn: "Al Qunfudhah", cityAr: "القنفذة" },
  { countryEn: "United Arab Emirates", countryAr: "الإمارات العربية المتحدة", flag: "🇦🇪", cityEn: "Dubai", cityAr: "دبي" },
  { countryEn: "United Arab Emirates", countryAr: "الإمارات العربية المتحدة", flag: "🇦🇪", cityEn: "Abu Dhabi", cityAr: "أبوظبي" },
  { countryEn: "United Arab Emirates", countryAr: "الإمارات العربية المتحدة", flag: "🇦🇪", cityEn: "Sharjah", cityAr: "الشارقة" },
  { countryEn: "United Arab Emirates", countryAr: "الإمارات العربية المتحدة", flag: "🇦🇪", cityEn: "Al Ain", cityAr: "العين" },
  { countryEn: "Kuwait", countryAr: "الكويت", flag: "🇰🇼", cityEn: "Kuwait City", cityAr: "مدينة الكويت" },
  { countryEn: "Kuwait", countryAr: "الكويت", flag: "🇰🇼", cityEn: "Al Ahmadi", cityAr: "الأحمدي" },
  { countryEn: "Kuwait", countryAr: "الكويت", flag: "🇰🇼", cityEn: "Hawalli", cityAr: "حولي" },
  { countryEn: "Kuwait", countryAr: "الكويت", flag: "🇰🇼", cityEn: "Al Jahra", cityAr: "الجهراء" },
  { countryEn: "Qatar", countryAr: "قطر", flag: "🇶🇦", cityEn: "Doha", cityAr: "الدوحة" },
  { countryEn: "Qatar", countryAr: "قطر", flag: "🇶🇦", cityEn: "Al Wakrah", cityAr: "الوكرة" },
  { countryEn: "Qatar", countryAr: "قطر", flag: "🇶🇦", cityEn: "Lusail", cityAr: "لوسيل" },
  { countryEn: "Qatar", countryAr: "قطر", flag: "🇶🇦", cityEn: "Al Khor", cityAr: "الخور" },
  { countryEn: "Bahrain", countryAr: "البحرين", flag: "🇧🇭", cityEn: "Manama", cityAr: "المنامة" },
  { countryEn: "Bahrain", countryAr: "البحرين", flag: "🇧🇭", cityEn: "Muharraq", cityAr: "المحرق" },
  { countryEn: "Bahrain", countryAr: "البحرين", flag: "🇧🇭", cityEn: "Riffa", cityAr: "الرفاع" },
  { countryEn: "Bahrain", countryAr: "البحرين", flag: "🇧🇭", cityEn: "Isa Town", cityAr: "مدينة عيسى" },
  { countryEn: "Oman", countryAr: "عمان", flag: "🇴🇲", cityEn: "Muscat", cityAr: "مسقط" },
  { countryEn: "Oman", countryAr: "عمان", flag: "🇴🇲", cityEn: "Salalah", cityAr: "صلالة" },
  { countryEn: "Oman", countryAr: "عمان", flag: "🇴🇲", cityEn: "Sohar", cityAr: "صحار" },
  { countryEn: "Oman", countryAr: "عمان", flag: "🇴🇲", cityEn: "Nizwa", cityAr: "نزوى" },
];
